version: '2.4'
services: 
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: 1122334455ab
      MYSQL_DATABASE: hrdb
    volumes: 
      - db-data:/var/lib/mysql
  pma:
    image: nazarpc/phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_HOST: db
      UPLOAD_SIZE: 1G
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports: 
      - 80:80
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports: 
      - 3030:3030
volumes: 
  db-data: