version: '2.4'
services: 
  db:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: 1122334455ab
      MYSQL_DATABASE: hrdb
    volumes: 
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: nazarpc/phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_HOST: db
      UPLOAD_SIZE: 1G

volumes: 
  db-data: